# Generated by Django 5.0.6 on 2024-06-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='categoy',
            new_name='category',
        ),
    ]
